#!/bin/bash

#
# Libica test suite
#

verbosity=$1

out="./suite.out"

testcases=(
"libica_fips_test"

"libica_get_functionlist $verbosity"
"libica_get_version $verbosity"
"icastats_test $verbosity"

"libica_drbg_test $verbosity"

"libica_des_ecb_test $verbosity"
"libica_des_cbc_test $verbosity"
"libica_des_cfb_test $verbosity"
"libica_des_ofb_test $verbosity"
"libica_des_ctr_test $verbosity"

"libica_3des_ecb_test $verbosity"
"libica_3des_cbc_test $verbosity"
"libica_3des_cfb_test $verbosity"
"libica_3des_ofb_test $verbosity"
"libica_3des_ctr_test $verbosity"

"libica_aes128_test $verbosity"
"libica_aes192_test $verbosity"
"libica_aes256_test $verbosity"
"libica_aes_ecb_test $verbosity"
"libica_aes_cbc_test $verbosity"
"libica_aes_cfb_test $verbosity"
"libica_aes_ofb_test $verbosity"
"libica_aes_ctr_test $verbosity"
"libica_aes_gcm_test $verbosity"
"libica_aes_xts_test $verbosity"

"libica_cbccs_test $verbosity"
"libica_ccm_test $verbosity"
"libica_cmac_test $verbosity"

"libica_keygen_test $verbosity 1024 r"
"libica_keygen_test $verbosity 2048 r"
"libica_keygen_test $verbosity 3072 r"
"libica_keygen_test $verbosity 4096 r"
"libica_rsa_key_check_test $verbosity"
"libica_rsa_test $verbosity"

"libica_sha_test/libica_sha_test $verbosity libica_sha_test/sha_test_vectors/*"
)

echo -ne "" &> $out;
for (( i=1; i <= ${#testcases[@]}; i++ ))
do
	echo -ne "Running libica test suite (writing to "$out") ... "$i"/"${#testcases[@]}"\r";
	./${testcases[i-1]} >> $out 2>&1;
done
echo -ne "\n";
