#! /bin/bash

#all the stuff to get the version out of configure.in

verLine=`eval grep AM_INIT_AUTOMAKE configure.in`
version_w_paren=`eval 'echo $verLine | cut -b 25-'`
len=`eval 'echo $version_w_paren | wc -m'`
let "cutlen=$len-2"
version_string=`eval 'echo $version_w_paren | cut -b 1-$cutlen'`

version=`eval 'echo $version_string | cut -f 1-2 -d "."'`
release=`eval 'echo $version_string | cut -f 3-3 -d "."'`

Version="Version: $version"
Release="Release: $release"
setup="%setup -c libica-$version"

oldver=`eval grep Version: libica-*`
oldrel=`eval grep Release: libica-*`
oldset=`eval grep %setup libica-*`
cat libica-* | sed "s?$oldver?$Version?g" > ./tmp
cat tmp | sed "s?$oldrel?$Release?g" > ./tmp2
cat tmp2 | sed "s?$oldset?$setup?g" > ./tmp3
mv tmp3 libica-$version-$release.spec
rm -f tmp*
