.\" icainfo man page source
.\"
.\" use
.\"   groff -man -Tutf8 icainfo.1
.\" or
.\"   nroff -man icainfo.1
.\" to process this source
.\"
.TH ICAINFO 1 2022-08-22 IBM "icainfo user manual"
.SH NAME
icainfo \- print information about cryptographic functions supported by libica
.SH SYNOPSIS
.B icainfo
[-v | --version] [-h | --help] [-c | --list-curves] [-r | --list-rsa]
.SH DESCRIPTION
.B icainfo
prints a table that shows libica's support for various cryptographic
algorithms and information about FIPS support.

The icainfo output also indicates, whether it is in an error state.
Algorithms that are not FIPS approved are marked as blocked in all table
columns when running in FIPS mode. All algorithms are marked as blocked when
libica is in an error state.

Available hardware support is divided into two columns: dynamic hardware
means crypto cards, static hardware support means CPACF. Software support
is provided via openssl.

A shortened sample output is given below:
.P
.nf
      Cryptographic algorithm support
------------------------------------------------------
               |         hardware        |
 function      |   dynamic  |   static   |  software
---------------+------------+------------+------------
         SHA-1 |     no     |    yes     |    yes
       SHA-224 |     no     |    yes     |    yes
       SHA-256 |     no     |    yes     |    yes
       SHA-384 |     no     |    yes     |    yes
       SHA-512 |     no     |    yes     |    yes
         GHASH |     no     |    yes     |     no
         P_RNG |  blocked   |  blocked   |  blocked
  DRBG-SHA-512 |     no     |    yes     |    yes
        RSA ME |    yes     |     no     |    yes
       RSA CRT |    yes     |     no     |    yes
           ...
------------------------------------------------------
Built-in FIPS support: FIPS 140-3 mode active.
.fi
.SH OPTIONS
.IP "-v or --version"
show libica version and copyright
.IP "-h or --help"
display this help and exit
.IP "-c or --list-curves"
show supported elliptic curves
.IP "-r or --list-rsa"
show min and max supported RSA key lengths
.SH RETURN VALUE
.IP 1
unknown or invalid argument on invocation
.IP 0
successful program execution
.SH "SEE ALSO"
.BR icastats (1)

