.\" icainfo man page source
.\"
.\" use
.\"   groff -man -Tutf8 icainfo.1
.\" or
.\"   nroff -man icainfo.1
.\" to process this source
.\"
.TH ICAINFO 1 2013-12-06 IBM "icainfo user manual"
.SH NAME
icainfo \- show information about cryptographic functions supported by libica
.SH SYNOPSIS
.B icainfo
[-v | --version] [-h | --help] [--quiet | -q]
.SH DESCRIPTION
.B icainfo
displays all the cryptographic algorithms and modes of operation supported by
libica together with implementation details about software and hardware support.
.P
.nf
 function   |    # hardware     |     # software
------------+-------------------+----------------
  SHA-1     |        yes        |          yes
  SHA-224   |        yes        |          yes
  SHA-256   |        yes        |          yes
  SHA-384   |        yes        |          yes
  SHA-512   |        yes        |          yes
  PRNG      |        yes        |          yes
  RSA ME    |        yes        |          yes
  RSA CRT   |        yes        |          yes
  DES ECB   |        yes        |          yes
  DES CBC   |        yes        |          yes
 DES CBC CS |        yes        |          yes
  DES OFB   |        yes        |          yes
  DES CTR   |        yes        |          yes
 DES CTR LS |        yes        |          yes
DES CBC MAC |        yes        |          yes
  DES CMAC  |        yes        |          yes
 3DES ECB   |        yes        |          yes
 3DES CBC   |        yes        |          yes
3DES CBC CS |        yes        |          yes
 3DES OFB   |        yes        |          yes
 3DES CFB   |        yes        |          yes
 3DES CTR   |        yes        |          yes
3DES CTRLST |        yes        |          yes
3DES CBC MAC|        yes        |          yes
  3DES CMAC |        yes        |          yes
  AES ECB   |        yes        |          yes
  AES CBC   |        yes        |          yes
 AEC CBC CS |        yes        |          yes
  AES OFB   |        yes        |          yes
  AES CFB   |        yes        |          yes
  AES CTR   |        yes        |          yes
 AES CTRLST |        yes        |          yes
AES CBC MAC |        yes        |          yes
  AES CMAC  |        yes        |          yes
  AES CCM   |        yes        |          yes
.fi
.SH OPTIONS
.IP "-v or --version"
show libica version and copyright
.IP "-h or --help"
display this help and exit
.IP "-q or --quiet"
list table with algorithms, modes and software/hardware support
.SH RETURN VALUE
.IP 1
unknown or invalid argument on invocation
.IP 0
successful program execution
.SH "SEE ALSO"
.BR icastats (1)

